title: What the Font
description: "  A Fonty Blog for Fonty People"
header_text: ""
footer_text: I promise it stands for font
header_feature_image: ../uploads/what-the-f-.png
bannerheight: 60vmax
logo: ../uploads/wtf-logo.jpg
favicon: /uploads/favicon.ico
gridlayout: true
fixednavbar: false
upzoom: true
