title: What the Font
description: A Fonty Blog for Fonty People
header_text: A Fonty Blog for Fonty People
footer_text: I promise it stands for font
header_feature_image: ../uploads/joanna-kosinska-1_cmofspfso-unsplash.jpg
bannerheight: 100vh
logo: ../uploads/what-the-f-logo.png
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
